# -*- mode: ruby -*-
# vi: set ft=ruby :

$bootstrap = <<SCRIPT
#!/bin/bash
# basic setup for all guests

cat > /etc/hosts <<EOF
127.0.0.1       localhost

::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

192.168.56.201 cnode1

EOF

mkdir -p /root/.ssh
chmod 600 /root/.ssh
cp /home/vagrant/.ssh/authorized_keys /root/.ssh/authorized_keys
chown root:root /root/.ssh/authorized_keys

wget -O - http://12.am/jdk/repo-pub.key | apt-key add -
echo -e "deb http://12.am/jdk/ unstable non-free" > /etc/apt/sources.list.d/java.list
apt-get update
apt-get install -y git unzip oracle-java7-jdk

SCRIPT

$fab_setup = <<SCRIPT
#!/bin/bash
# Setup script for the ~/fab directory

#Copy Java and Ant to home dir:
mkdir ~/fab
cd ~/fab
wget http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.tar.bz2
tar xfv apache-ant-1.9.4-bin.tar.bz2 -C ~/fab
ln -s apache-ant-1.9.4 ant
ln -s /usr/lib/jvm/java-7-oracle java
rm apache-ant-1.9.4-bin.tar.bz2

echo -e "\n\nHost github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

# stress_compare clients don't need this repository, but if you want to run stress_compare from the node, uncomment this line:
#git clone -v git@github.com:riptano/automaton.git ~/git/automaton

SCRIPT

Vagrant.configure("2") do |config|

  id_rsa_pub = File.read(File.join(Dir.home, ".ssh", "id_rsa.pub"))
  # Use host SSH agent forwarding, so the VM can clone from private repos:
  config.ssh.forward_agent = true

  # A small guest to run the tests from:
  config.vm.define :cnode do |cnode|
    cnode.vm.box = "trusty"
    cnode.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    cnode.vm.provider :virtualbox do |vb|
      vb.name = 'cnode1'
      vb.customize ["modifyvm", :id, "--memory", "2048", "--groups", "/Cassandra_Vagrant"]
    end
    cnode.vm.network :private_network, ip: "192.168.56.201"
    cnode.vm.hostname = 'cnode1'
    config.vm.provision :shell, :inline => "echo '#{id_rsa_pub }' >> /home/vagrant/.ssh/authorized_keys && chmod 600 /home/vagrant/.ssh/authorized_keys"
    config.vm.provision :shell, :inline => "echo 'export JAVA_HOME=/usr/lib/jvm/java-7-oracle' >> /home/vagrant/.bashrc"
    cnode.vm.provision :shell, :inline => $bootstrap
    cnode.vm.provision :shell, privileged: false, :inline => $fab_setup
  end

end
